server:
  port: 8090

spring:
  application:
    name: email-center

management:
  endpoints:
    web:
      exposure:
        include: "*"

endpoint:
  web:
    exposure:
      include: prometheus

eureka:
  client:
    service-url:
      defaultZone: http://docker.for.mac.localhost:9000/eureka
    register-with-eureka: true
    fetch-registry: true
